
#MAGICAL MUSHROOM SOUP MESSAGES

Cant_Fly_Message: '븎You already have a active fly effect!'
soup_used_Message: '브You used 1 Magical Mushroom Soup'
sec_10_left: '븎10 브left of your flying soup!'
sec_9_left: '븎9 브left of your flying soup!'
sec_8_left: '븎8 브left of your flying soup!'
sec_7_left: '븎7 브left of your flying soup!'
sec_6_left: '븎6 브left of your flying soup!'
sec_5_left: '븎5 브left of your flying soup!'
sec_4_left: '븎4 브left of your flying soup!'
sec_3_left: '븎3 브left of your flying soup!'
sec_2_left: '븎2 브left of your flying soup!'
sec_1_left: '븎1 브left of your flying soup!'
over: '븎Your magical mushrom soup is over'